//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistanceLearningCore.Model.StaffModel
{
    using System;
    using System.Collections.Generic;
    
    public abstract partial class Person
    {
        public int Id { get; set; }
        public string Surname { get; set; }
        public string FirstName { get; set; }
        public string Othername { get; set; }
        public string MaidenName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string StateofOrigin { get; set; }
        public string PhoneNo { get; set; }
        public string EmailAddress { get; set; }
        public string Address { get; set; }
        public string Gender { get; set; }
        public string LoginID { get; set; }
        public string PostalAddress { get; set; }
        public string PlaceofBirth { get; set; }
        public string Picture { get; set; }
        public string LGA { get; set; }
        public string MarritalStatus { get; set; }
        public string HealthStatus { get; set; }
        public string Religion { get; set; }
        public string Signature { get; set; }
        public Nullable<bool> IsEmployed { get; set; }
        public Nullable<bool> IsFinished { get; set; }
        public Nullable<bool> IsSPT { get; set; }
        public Nullable<bool> IsDE { get; set; }
        public Nullable<bool> IsVerified { get; set; }
        public string VerifiedBy { get; set; }
        public Nullable<System.DateTime> DateVerified { get; set; }
        public Nullable<bool> IncompleteOLevel { get; set; }
        public string NxtFullName { get; set; }
        public string NxtEmail { get; set; }
        public string NxtPhoneNo { get; set; }
        public string NxtRelationship { get; set; }
    }
}
