//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistanceLearningCore.Model.StudentModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applicant : Person
    {
        public Applicant()
        {
            this.StudentExaminations = new HashSet<StudentExamination>();
            this.StudentSchools = new HashSet<StudentSchoolxx>();
            this.Applications = new HashSet<Application>();
            this.ApplicantProgresses = new HashSet<ApplicantProgressxx>();
            this.Employments = new HashSet<Employmentxx>();
        }
    
        public Nullable<int> AdmissionId { get; set; }
        public string ApplicationNo { get; set; }
    
        public virtual ICollection<StudentExamination> StudentExaminations { get; set; }
        public virtual ICollection<StudentSchoolxx> StudentSchools { get; set; }
        public virtual ICollection<Application> Applications { get; set; }
        public virtual ICollection<ApplicantProgressxx> ApplicantProgresses { get; set; }
        public virtual ICollection<Employmentxx> Employments { get; set; }
    }
}
