//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistanceLearningCore.Model.StudentModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coursexx
    {
        public Coursexx()
        {
            this.Curricula = new HashSet<Curriculum>();
        }
    
        public int Id { get; set; }
        public string CourseCode { get; set; }
        public string CourseTitle { get; set; }
        public Nullable<int> deptId { get; set; }
    
        public virtual ICollection<Curriculum> Curricula { get; set; }
        public virtual Departmentxx Department { get; set; }
    }
}
