//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistanceLearningCore.Model.StudentModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curriculum
    {
        public Curriculum()
        {
            this.Curriculum1 = new HashSet<Curriculum>();
            this.StudentRegistrations = new HashSet<StudentRegistrationxx>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public Nullable<int> ReqId { get; set; }
        public Nullable<int> Prequisite { get; set; }
        public Nullable<int> CourseId { get; set; }
        public Nullable<int> Unit { get; set; }
        public Nullable<int> LH { get; set; }
        public Nullable<System.DateTime> DateTimeStamp { get; set; }
        public Nullable<int> PH { get; set; }
    
        public virtual ICollection<Curriculum> Curriculum1 { get; set; }
        public virtual Curriculum Curriculum2 { get; set; }
        public virtual ICollection<StudentRegistrationxx> StudentRegistrations { get; set; }
        public virtual Requirement Requirement { get; set; }
        public virtual Coursexx Cours { get; set; }
    }
}
