//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistanceLearningCore.Model.StudentModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departmentxx
    {
        public Departmentxx()
        {
            this.Courses = new HashSet<Coursexx>();
            this.Programmes = new HashSet<Programme>();
        }
    
        public int Id { get; set; }
        public string DeptAcronymns { get; set; }
        public string DeptName { get; set; }
        public Nullable<int> FacId { get; set; }
        public string DeptCode { get; set; }
    
        public virtual ICollection<Coursexx> Courses { get; set; }
        public virtual Facultyxxx Faculty { get; set; }
        public virtual ICollection<Programme> Programmes { get; set; }
    }
}
