//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistanceLearningCore.Model.StudentModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacultyReq : Requirement
    {
        public Nullable<int> LevId { get; set; }
        public Nullable<int> FacId { get; set; }
    
        public virtual Facultyxxx Faculty { get; set; }
    }
}
