//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistanceLearningCore.Model.StudentModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgrammeLevel
    {
        public ProgrammeLevel()
        {
            this.AdmissionProgrammes = new HashSet<AdmissionProgramme>();
            this.ProgrammeReqs = new HashSet<ProgrammeReq>();
            this.StudentCatLevels = new HashSet<StudentCatLevel>();
        }
    
        public int Id { get; set; }
        public string ProgLevDescription { get; set; }
        public Nullable<int> LevId { get; set; }
        public Nullable<int> ProgId { get; set; }
    
        public virtual ICollection<AdmissionProgramme> AdmissionProgrammes { get; set; }
        public virtual Programme Programme { get; set; }
        public virtual ICollection<ProgrammeReq> ProgrammeReqs { get; set; }
        public virtual ICollection<StudentCatLevel> StudentCatLevels { get; set; }
    }
}
