//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistanceLearningCore.Model.StudentModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentLevel
    {
        public StudentLevel()
        {
            this.StudentRegistrations = new HashSet<StudentRegistrationxx>();
        }
    
        public int Id { get; set; }
        public int SessId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> StudLevelId { get; set; }
    
        public virtual Studentxx Student { get; set; }
        public virtual StudentCatLevel StudentCatLevel { get; set; }
        public virtual ICollection<StudentRegistrationxx> StudentRegistrations { get; set; }
    }
}
