//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistanceLearningCore.Model.StudentModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StudentElearningEntities : DbContext
    {
        public StudentElearningEntities()
            : base("name=StudentElearningEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<StudentCatLevel> StudentCatLevels { get; set; }
        public virtual DbSet<StudentDocumentxcx> StudentDocumentxcxes { get; set; }
        public virtual DbSet<StudentExamination> StudentExaminations { get; set; }
        public virtual DbSet<StudentLevel> StudentLevels { get; set; }
        public virtual DbSet<StudentRegistrationxx> StudentRegistrationxxes { get; set; }
        public virtual DbSet<StudentSchoolxx> StudentSchoolxxes { get; set; }
        public virtual DbSet<SessionSem> SessionSems { get; set; }
        public virtual DbSet<Curriculum> Curricula { get; set; }
        public virtual DbSet<AdmissionProcessing> AdmissionProcessings { get; set; }
        public virtual DbSet<Application> Applications { get; set; }
        public virtual DbSet<ApplicantProgressxx> ApplicantProgressxxes { get; set; }
        public virtual DbSet<StudentCategoryxxx> StudentCategoryxxxes { get; set; }
        public virtual DbSet<Requirement> Requirements { get; set; }
        public virtual DbSet<Awardxx> Awardxxes { get; set; }
        public virtual DbSet<Coursexx> Coursexxes { get; set; }
        public virtual DbSet<Departmentxx> Departmentxxes { get; set; }
        public virtual DbSet<Stepxx> Stepxxes { get; set; }
        public virtual DbSet<Facultyxxx> Facultyxxxes { get; set; }
        public virtual DbSet<AdmissionProgramme> AdmissionProgrammes { get; set; }
        public virtual DbSet<Programme> Programmes { get; set; }
        public virtual DbSet<ProgrammeLevel> ProgrammeLevels { get; set; }
        public virtual DbSet<ExaminationSubject> ExaminationSubjects { get; set; }
        public virtual DbSet<Employmentxx> Employmentxxes { get; set; }
    }
}
