//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistanceLearningCore.Model.StudentModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentSchoolxx
    {
        public int Id { get; set; }
        public string SchoolName { get; set; }
        public string Course { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public int StudentId { get; set; }
        public string Qualification { get; set; }
        public string CGPA { get; set; }
        public string Class { get; set; }
    
        public virtual Applicant Applicant { get; set; }
    }
}
