//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistanceLearningCore.Model.StudentModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentDocumentxcx
    {
        public int Id { get; set; }
        public string DocumentDescription { get; set; }
        public string DocumentPath { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> PerId { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
