//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistanceLearningCore.Model.StudentModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentCatLevel
    {
        public StudentCatLevel()
        {
            this.StudentLevels = new HashSet<StudentLevel>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public Nullable<int> StudCatId { get; set; }
        public Nullable<int> ProgLevId { get; set; }
    
        public virtual ICollection<StudentLevel> StudentLevels { get; set; }
        public virtual StudentCategoryxxx StudentCategory { get; set; }
        public virtual ProgrammeLevel ProgrammeLevel { get; set; }
    }
}
