//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistanceLearningCore.Model.StudentModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentExamination
    {
        public StudentExamination()
        {
            this.ExaminationSubjects = new HashSet<ExaminationSubject>();
        }
    
        public int Id { get; set; }
        public string ExamBody { get; set; }
        public string ExamCentre { get; set; }
        public string ExamNo { get; set; }
        public int StudentId { get; set; }
        public string ExamYear { get; set; }
        public Nullable<bool> IsFirst { get; set; }
        public string VerificationComment { get; set; }
        public Nullable<bool> IsVerified { get; set; }
        public Nullable<System.DateTime> VerificationDate { get; set; }
        public string VerifiedBy { get; set; }
    
        public virtual Applicant Applicant { get; set; }
        public virtual ICollection<ExaminationSubject> ExaminationSubjects { get; set; }
    }
}
