//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistanceLearningCore.Model.Payment
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChildPayment : Payment
    {
        public ChildPayment()
        {
            this.PaymentItems = new HashSet<PaymentItem>();
        }
    
        public string PayDescription { get; set; }
    
        public virtual ICollection<PaymentItem> PaymentItems { get; set; }
    }
}
