//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistanceLearningCore.Model.Payment
{
    using System;
    using System.Collections.Generic;
    
    public abstract partial class PayCategory
    {
        public PayCategory()
        {
            this.PaymentConfigurations = new HashSet<PaymentConfiguration>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public Nullable<int> PayId { get; set; }
    
        public virtual ICollection<PaymentConfiguration> PaymentConfigurations { get; set; }
        public virtual Payment Payment { get; set; }
    }
}
