//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistanceLearningCore.Model.Payment
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentItem
    {
        public int Id { get; set; }
        public Nullable<int> PayId { get; set; }
        public Nullable<float> Amount { get; set; }
        public Nullable<int> ItemId { get; set; }
    
        public virtual PaymentConfiguration PaymentConfiguration { get; set; }
        public virtual ChildPayment ChildPayment { get; set; }
    }
}
