//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistanceLearningCore.Model.Payment
{
    using System;
    using System.Collections.Generic;
    
    public abstract partial class Payment
    {
        public Payment()
        {
            this.PayCategories = new HashSet<PayCategory>();
        }
    
        public int Id { get; set; }
        public string PaymentDescription { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        public virtual ICollection<PayCategory> PayCategories { get; set; }
    }
}
