//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistanceLearningCore.Model.Payment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public Session()
        {
            this.SessionPayments = new HashSet<SessionPayment>();
            this.SessionSems = new HashSet<SessionSem>();
            this.StudentLevels = new HashSet<StudentLevel>();
        }
    
        public int Id { get; set; }
        public string SessionDescription { get; set; }
        public Nullable<bool> IsOpen { get; set; }
        public Nullable<System.DateTime> ClosingDate { get; set; }
    
        public virtual ICollection<SessionPayment> SessionPayments { get; set; }
        public virtual ICollection<SessionSem> SessionSems { get; set; }
        public virtual ICollection<StudentLevel> StudentLevels { get; set; }
    }
}
