//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistanceLearningCore.Model.Payment
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessionSemPayment : PayCategory
    {
        public Nullable<int> SessId { get; set; }
    
        public virtual SessionSem SessionSem { get; set; }
    }
}
