//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistanceLearningDomain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admission
    {
        public Admission()
        {
         
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string AdmissionDescription { get; set; }
        public Nullable<System.DateTime> ClosingDate { get; set; }
        public Nullable<bool> IsOpen { get; set; }
        public Nullable<int> SessId { get; set; }
        public Nullable<float> ApplicationAmount { get; set; }
    
    }
}
