//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistanceLearningDomain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Award
    {
        public Award()
        {
            
        }
    
        public int Id { get; set; }
        public string AwardDescription { get; set; }
        public string AwardAcronymns { get; set; }
        public Nullable<int> SchId { get; set; }
        public Nullable<int> Duration { get; set; }
    
      
    }
}
