//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistanceLearningDomain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Designation
    {
        public Designation()
        {
            this.Staffs = new HashSet<Staff>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsAdmin { get; set; }
    
        public virtual IEnumerable<Staff> Staffs { get; set; }
    }
}
