//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistanceLearningDomain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMTPProxy
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public string SMTPServer { get; set; }
        public string SMTPPort { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<bool> SSLEnabled { get; set; }
        public Nullable<int> SMTPTimeout { get; set; }
    }
}
