//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistanceLearningDomain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentInvoice : Invoice
    {
        public Nullable<int> PrecisionId { get; set; }
        public Nullable<int> StudentId { get; set; }
    
        public virtual StudentPrecision StudentPrecision { get; set; }
    }
}
