//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistanceLearningCore.Model.Administration
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ElearningAdminEntities : DbContext
    {
        public ElearningAdminEntities()
            : base("name=ElearningAdminEntities")
        {
            PersonAdms = Set<PersonAdm>();
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admission> Admissions { get; set; }
        public virtual DbSet<Award> Awards { get; set; }
        public virtual DbSet<CourseRole> CourseRoles { get; set; }
        public virtual DbSet<Cours> Courses { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Faculty> Faculties { get; set; }
        public virtual DbSet<Level> Levels { get; set; }
        public virtual DbSet<ProgrammeAdmin> ProgrammeAdmins { get; set; }
        public virtual DbSet<Semester> Semesters { get; set; }
        public virtual DbSet<Session> Sessions { get; set; }
        public virtual DbSet<SessionSem> SessionSems { get; set; }
        public virtual DbSet<SMTPProxy> SMTPProxies { get; set; }
        public virtual DbSet<Step> Steps { get; set; }
        public virtual DbSet<StudentCategory> StudentCategories { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
        public virtual DbSet<School> Schools { get; set; }
        public virtual DbSet<ProgrammeLevelAdmin> ProgrammeLevelAdmins { get; set; }
        public virtual DbSet<StudentCatLevelxxx> StudentCatLevelxxxes { get; set; }
        public virtual DbSet<StudentLevel> StudentLevels { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<ApplicantProgress> ApplicantProgresses { get; set; }
        public virtual DbSet<AdmissionProgrammeAdmin> AdmissionProgrammeAdmins { get; set; }
        public virtual DbSet<ApplicationAdmin> ApplicationAdmins { get; set; }
        internal virtual DbSet<PersonAdm> PersonAdms { get; set; }
    }
}
