//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistanceLearningCore.Model.Administration
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicantAdmin : PersonAdm
    {
        public ApplicantAdmin()
        {
            this.ApplicantProgresses = new HashSet<ApplicantProgress>();
            this.Applications = new HashSet<ApplicationAdmin>();
        }
    
        public Nullable<int> AdmissionId { get; set; }
        public string ApplicationNo { get; set; }
    
        public virtual Admission Admission { get; set; }
        public virtual ICollection<ApplicantProgress> ApplicantProgresses { get; set; }
        public virtual ICollection<ApplicationAdmin> Applications { get; set; }
    }
}
