//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistanceLearningCore.Model.Administration
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicantProgress
    {
        public int Id { get; set; }
        public Nullable<int> StepId { get; set; }
        public Nullable<int> AppId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        public virtual Step Step { get; set; }
        public virtual ApplicantAdmin Applicant { get; set; }
    }
}
