//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistanceLearningCore.Model.Administration
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.Courses = new HashSet<Cours>();
            this.Programmes = new HashSet<ProgrammeAdmin>();
        }
    
        public int Id { get; set; }
        public string DeptAcronymns { get; set; }
        public string DeptName { get; set; }
        public Nullable<int> FacId { get; set; }
        public string DeptCode { get; set; }
    
        public virtual ICollection<Cours> Courses { get; set; }
        public virtual Faculty Faculty { get; set; }
        public virtual ICollection<ProgrammeAdmin> Programmes { get; set; }
    }
}
