//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistanceLearningCore.Model.Administration
{
    using System;
    using System.Collections.Generic;
    
    public partial class Level
    {
        public Level()
        {
            this.ProgrammeLevels = new HashSet<ProgrammeLevelAdmin>();
        }
    
        public int Id { get; set; }
        public string LevelDescription { get; set; }
    
        public virtual ICollection<ProgrammeLevelAdmin> ProgrammeLevels { get; set; }
    }
}
