//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistanceLearningCore.Model.Administration
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgrammeAdmin
    {
        public ProgrammeAdmin()
        {
            this.ProgrammeLevels = new HashSet<ProgrammeLevelAdmin>();
        }
    
        public int Id { get; set; }
        public string ProgrammeDescription { get; set; }
        public string ProgrammeCode { get; set; }
        public Nullable<int> AwardId { get; set; }
        public Nullable<bool> IsFullTime { get; set; }
        public Nullable<int> DeptID { get; set; }
        public Nullable<System.DateTime> DateTimeStamp { get; set; }
    
        public virtual Award Award { get; set; }
        public virtual Department Department { get; set; }
        public virtual ICollection<ProgrammeLevelAdmin> ProgrammeLevels { get; set; }
    }
}
