//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistanceLearningCore.Model.Administration
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgrammeLevelAdmin
    {
        public ProgrammeLevelAdmin()
        {
            this.StudentCatLevels = new HashSet<StudentCatLevelxxx>();
            this.AdmissionProgrammes = new HashSet<AdmissionProgrammeAdmin>();
        }
    
        public int Id { get; set; }
        public string ProgLevDescription { get; set; }
        public Nullable<int> LevId { get; set; }
        public Nullable<int> ProgId { get; set; }
    
        public virtual Level Level { get; set; }
        public virtual ProgrammeAdmin Programme { get; set; }
        public virtual ICollection<StudentCatLevelxxx> StudentCatLevels { get; set; }
        public virtual ICollection<AdmissionProgrammeAdmin> AdmissionProgrammes { get; set; }
    }
}
