//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistanceLearningCore.Model.Administration
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentLevel
    {
        public int Id { get; set; }
        public int SessId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> StudLevelId { get; set; }
    
        public virtual Session Session { get; set; }
        public virtual StudentCatLevelxxx StudentCatLevel { get; set; }
        public virtual Student Student { get; set; }
    }
}
